name: Java CI

on: [push]

jobs:
  checksecret:
    name: check if PLSPLUSQG_USERNAME is set in github secrets
    runs-on: ubuntu-latest
    outputs:
      is_MY_SECRET_set: ${{ steps.checksecret_job.outputs.is_MY_SECRET_set }}
    steps:
      - name: Check whether secrets are available
        id: checksecret_job
        env:
          MY_SECRET: ${{ secrets.PLSPLUSQG_USERNAME }}
        run: |
          echo "is_MY_SECRET_set: ${{ env.MY_SECRET != '' }}"
          echo "::set-output name=is_MY_SECRET_set::${{ env.MY_SECRET != '' }}"
  build:
    needs: [ checksecret ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup Test Integration Credentials
        run: |
          echo "---" >  api/PLSplusQG-SpringBootClient/src/test/resources/pdev.yml
          echo "PLS_USERNAME: $PLSNAME" >>  api/PLSplusQG-SpringBootClient/src/test/resources/pdev.yml
          echo "PLS_PASSWORD: $PLSPASS" >>  api/PLSplusQG-SpringBootClient/src/test/resources/pdev.yml
          echo "config setup:"
          cat  api/PLSplusQG-SpringBootClient/src/test/resources/pdev.yml
          echo "config done"
        env:
          PLSNAME: ${{secrets.PLSPLUSQG_USERNAME}}
          PLSPASS: ${{secrets.PLSPLUSQG_PASSWORD}}
      - name: Build with Maven Full
        if: needs.checksecret.outputs.is_MY_SECRET_set == 'true'
        run: cd api && mvn --batch-mode --update-snapshots verify

      - name: Build with Maven Exclude External Integration Tests
        if: needs.checksecret.outputs.is_MY_SECRET_set == 'false'
        run: cd api && mvn --batch-mode --update-snapshots verify  -DexcludedGroups=ExternalIntegrationTest


      - name: Package artifacts
        if: needs.checksecret.outputs.is_MY_SECRET_set == 'true'
        run: |
         mkdir staging
         cp  api/PLSplusQG-SpringBootClient/target/PLS*.jar staging
         cp -r  api/PLSplusQG-SpringBootClient/target/generated-sources/swagger/docs staging
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: needs.checksecret.outputs.is_MY_SECRET_set == 'true'
        with:
          name: Package
          path: staging
