name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Test Integration Credentials
        run: |
          echo "---" > api/PLSplusQG-SwaggerClient/src/test/resources/pdev.yml
          echo "PLS_USERNAME: $PLSNAME" >> api/PLSplusQG-SwaggerClient/src/test/resources/pdev.yml
          echo "PLS_PASSWORD: $PLSPASS" >> api/PLSplusQG-SwaggerClient/src/test/resources/pdev.yml
          echo "config setup:"
          cat api/PLSplusQG-SwaggerClient/src/test/resources/pdev.yml
          echo "config done"
        env:
          PLSNAME: ${{secrets.PLSPLUSQG_USERNAME}}
          PLSPASS: ${{secrets.PLSPLUSQG_PASSWORD}}
      - name: Build with Maven
        run: cd api && mvn --batch-mode --update-snapshots verify

      - run: |
         mkdir staging
         cp api/PLSplusQG-SwaggerClient/target/*.jar staging
         cp api/PLSplusQG-SwaggerClient/target/generated-sources/swagger/docs staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
